### ISSUE TITLE
Food class negative subtraction

### ISSUE THREAD

**Issue by rodigu** [Liu-Hy/Food-Bank-Network-Simulation#21]
@Liu-Hy 

Food class' subtraction function doesn't seem to account for the case when an order is greater than the available quantity.

Is this the intended behavior?

I should say that I would prefer it to still perform the subtraction (even if we end up with negative quantities) and the negative be handled outside the `subtract` func.

Related to #20 and #1

**Comment by rodigu** [comment]
It would actually be helpful if it does return a df with negative quantities.
I will use that in helping me estimate future unmet demand for the Food Bank.

**Comment by Liu-Hy** [comment]
I'll try that. 
Question: When you order more than it has, the remaining shelf live of the negative valued food makes no sense. Can I simply set MAX_DAYS?

**Comment by rodigu** [comment]
Maybe a `can_subtract` helper function in `Food` that takes in an order and returns whether a subtraction would make some quantity negative. It could return the new Food too if the subtraction is valid since subtract already seems like a very intense function.

**Comment by rodigu** [comment]
> I'll try that. Question: When you order more than it has, the remaining shelf live of the negative valued food makes no sense. Can I simply set MAX_DAYS?

It would be good for me to still have it return negative food. Here is how I would be using this:
```python
    def next_week_storage_estimate(self):
        """Next week's storage considering last week's demand
        """
        _, future_storage = self.storage.subtract(self.last_week_aggregate_demand(), inplace=False)
        return future_storage

    def future_unmet_demand(self):
        future_storage = self.next_week_storage_estimate()
        return future_storage[future_storage['quantity'] < 0]
```

**Comment by rodigu** [comment]
If the subtract function already does return negative without checking, we can keep it like that. We just need to make sure we know that is a thing.

From my simulations of the foodbank, it doesn't seem like things break (none of the Food instances I checked went negative)

**Comment by rodigu** [comment]
@lucianli123 will actually need to keep this in mind to not get food from the food banks such that the quantity goes negative

**Comment by Liu-Hy** [comment]
In my implementation for the pantry owner to order food, they never order food more than foodbanks have

**Comment by rodigu** [comment]
> In my implementation for the pantry owner to order food, they never order food more than foodbanks have

Yeah, that makes sense. I think we can just handle negative quantities (make sure it doesn't happen) outside of the subtract function

**Comment by Liu-Hy** [comment]
I extended the method. The parameter was also renamed. It should work now.
