### ISSUE TITLE
Main function of Foodbank class

### ISSUE THREAD

**Issue by Liu-Hy** [Liu-Hy/Food-Bank-Network-Simulation#8]
@rodigu, can you implement a main function of foodbank plz? No need to buy or share food, by calling run_one_day(), it receives newly donated food, lets pantries run sequentially, and gets aggregate waste and utility. I hope to have some result on the pantries of a bank before presentation.

**Comment by rodigu** [comment]
Was implemented with d41c85fcdbb3cfa8eadc9417f632cae777a30f4d

Let me know if I missed something

**Comment by Liu-Hy** [comment]
Can you generate daily donated food and add it to inventory?

**Comment by Liu-Hy** [comment]
> Can you generate daily donated food and add it to inventory?

Just two lines of code. I'll do that.

**Comment by rodigu** [comment]
Thanks!
